#
# Trafex
#
FROM alpine:3.15

# Setup document root
WORKDIR /var/www/html

# Install packages and remove default server definition
RUN apk add --no-cache \
  curl \
  nginx \
  php7 \
  php7-ctype \
  php7-curl \
  php7-dom \
  php7-fpm \
  php7-gd \
  php7-intl \
  php7-mbstring \
  php7-mysqli \
  php7-opcache \
  php7-openssl \
  php7-phar \
  php7-session \
  php7-xml \
  php7-xmlreader \
  php7-zlib \
  supervisor


# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody.nobody /var/www/html /run /var/lib/nginx /var/log/nginx

# Switch to use a non-root user from here on
USER nobody

# Add application
COPY --chown=nobody /public /var/www/html/

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

#
# added by WEDO
#



ARG XDEBUG

USER root

RUN ln -s /usr/sbin/php-fpm7 /usr/sbin/php-fpm

RUN apk add --no-cache git php7-tokenizer php7-fileinfo php7-xmlwriter php7-pdo php7-pdo_mysql openssh php7-exif \
    && if [ "$XDEBUG" = "true" ]; then apk add --no-cache php7-xdebug; fi \
    && rm -rf /tmp/* \
    && rm -rf /var/cache/apk/*

COPY --from=composer /usr/bin/composer /usr/bin/composer

# SSH for XDebug
RUN ssh-keygen -t rsa -q -f "/root/.ssh/id_rsa" -N "" && ssh-keygen -A
RUN echo "root:T653@2eyY@7er6@upX4" | chpasswd
RUN echo "StrictHostKeyChecking=no" >> /etc/ssh/ssh_config
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config


# TODO перевірити чи буде composer
# TODO перевірити папку ublic
