apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-queue
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-queue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-queue
    spec:
      containers:
        - name: backend-queue-sha256-1
          image: 788908097958.dkr.ecr.eu-central-1.amazonaws.com/project-versions:latest
          imagePullPolicy: Always
          command: ["php", "artisan", "queue:work", "--queue=default"]
          #command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: frankfurt-config
            - secretRef:
                name: frankfurt-secret
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

