###
GET http://127.0.0.1:8000/api/bookmarks
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE http://127.0.0.1:8000/api/bookmarks/
Authorization: Bearer {{token}}
Content-Type: application/json
