###
GET http://127.0.0.1:8000/api/notifications
Authorization: Bearer {{token}}
Content-Type: application/json


###
PATCH http://127.0.0.1:8000/api/notifications/1
Authorization: Bearer {{token}}
Content-Type: application/json


###
PATCH http://127.0.0.1:8000/api/notifications/reads
Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "notifications": [1,3,4,5]
 }
