name: Thefans-DEV

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 7k#&2-Dkf8wGSgp
          MYSQL_DATABASE: thefans
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci.production.example', '.env');"

      - name: Install composer dependencies
        run: composer update --ignore-platform-reqs

      - name: Set required directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migration database and seeds
        run: |
          php artisan migrate
          php artisan db:seed

      - name: Run Test phpunit
        run: vendor/bin/phpunit

  build:
      runs-on: ubuntu-latest
      needs: [ test ]

      steps:
        - uses: actions/checkout@v2

        - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.dev.example', '.env');"

        - name: Install NPM dependencies
          run: npm install

        - name: Minify CSS and JS files
          run: npm run build

        - name: Install composer dependencies
          run: composer install --no-scripts --no-interaction --ignore-platform-reqs --prefer-dist

        - name: Set required directory permissions
          run: chmod -R 777 storage bootstrap/cache

        - name: Copy repository contents via scp
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "., !docker"
            target: "/var/www/CreatorNetwork"

#  build:
#    runs-on: ubuntu-latest
#    needs: [ test ]
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Deployment
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          username: ${{ secrets.SSH_USERNAME }}
#
#          script: |
#            cd /var/www/CreatorNetwork
#            git pull origin backend
#            export NVM_DIR=~/.nvm
#            source ~/.nvm/nvm.sh
#            bash server_deploy.sh
#
#
